name: Backend Deployment to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build and Package
        run: mvn clean package

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is a popular action for deploying to Heroku, but check for the latest version.
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "your-heroku-app-name"
          heroku_email: "your-email@example.com"
          usedocker: true
          healthcheck: "https://your-heroku-app-name.herokuapp.com/"
